apiVersion: v1
kind: Service
metadata:
  name: {{ include "context-aware-email-reply.fullname" . }}-backend
  labels:
    app: {{ include "context-aware-email-reply.name" . }}-backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
  - port: {{ .Values.service.backend.port }}
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: {{ include "context-aware-email-reply.name" . }}-backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "context-aware-email-reply.fullname" . }}-frontend
  labels:
    app: {{ include "context-aware-email-reply.name" . }}-frontend
spec:
  type: {{ .Values.service.frontend.type }}
  ports:
  - port: {{ .Values.service.frontend.port }}
    targetPort: 8501
    protocol: TCP
    name: http
  selector:
    app: {{ include "context-aware-email-reply.name" . }}-frontend
